[package]
name = "gc_input_viewer"
version = "0.1.0"
authors = ["Isaac Lozano <109lozanoi@gmail.com>"]
edition = "2018"

[dependencies]
dtm2txt = {path = "../dtm2txt"}
serialport = "3.1.0"

[dependencies.sdl2]
version = "0.31.0"
features = ["image", "gfx"]